# Generated by Django 5.0.3 on 2025-11-16 04:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("articles", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_views", models.IntegerField(default=0)),
                ("unique_views", models.IntegerField(default=0)),
                ("avg_reading_time", models.FloatField(default=0.0)),
                ("completion_rate", models.FloatField(default=0.0)),
                ("shares_count", models.IntegerField(default=0)),
                ("likes_count", models.IntegerField(default=0)),
                ("comments_count", models.IntegerField(default=0)),
                ("search_views", models.IntegerField(default=0)),
                ("direct_views", models.IntegerField(default=0)),
                ("referral_views", models.IntegerField(default=0)),
                ("views_last_7_days", models.IntegerField(default=0)),
                ("views_last_30_days", models.IntegerField(default=0)),
                ("views_last_90_days", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="articles.article",
                    ),
                ),
            ],
            options={
                "ordering": ["-views_last_30_days"],
            },
        ),
        migrations.CreateModel(
            name="DailyAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("page", "Page"),
                            ("topic", "Topic"),
                            ("home", "Home"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_id", models.UUIDField(blank=True, null=True)),
                ("date", models.DateField()),
                ("total_views", models.IntegerField(default=0)),
                ("unique_views", models.IntegerField(default=0)),
                ("avg_time_on_page", models.FloatField(default=0.0)),
                ("bounce_rate", models.FloatField(default=0.0)),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "date"],
                        name="analytics_d_content_ffa5ac_idx",
                    ),
                    models.Index(fields=["date"], name="analytics_d_date_bf58fd_idx"),
                ],
                "unique_together": {("content_type", "object_id", "date")},
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("page", "Page"),
                            ("topic", "Topic"),
                            ("home", "Home"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_id", models.UUIDField(blank=True, null=True)),
                ("url", models.CharField(max_length=500)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("referrer", models.URLField(blank=True)),
                ("time_on_page", models.IntegerField(blank=True, null=True)),
                ("is_bounce", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="analytics_p_content_1e4e49_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="analytics_p_timesta_835321_idx"
                    ),
                    models.Index(
                        fields=["user"], name="analytics_p_user_id_23554e_idx"
                    ),
                    models.Index(
                        fields=["session_id"], name="analytics_p_session_a580f2_idx"
                    ),
                ],
            },
        ),
    ]
