# Generated by Django 4.2.26 on 2025-11-16 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("users", "0002_add_saas_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="marketing_emails",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="default_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_users",
                to="accounts.account",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="trial_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
