# Generated by Django 4.2.26 on 2025-11-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_email_notifications_user_marketing_emails_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
