# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='topic',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='page',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='accounts.account'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('account', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('account', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('account', 'slug')},
        ),
    ]
