# Generated by Django 4.2.7

from django.db import migrations

def set_default_account(apps, schema_editor):
    """
    Set a default account for existing articles, topics, and pages
    """
    Account = apps.get_model('accounts', 'Account')
    Article = apps.get_model('articles', 'Article')
    Topic = apps.get_model('articles', 'Topic')
    Page = apps.get_model('articles', 'Page')
    User = apps.get_model('users', 'User')
    
    # Get the first user to be the owner
    owner = User.objects.first()
    if not owner:
        return  # No users exist, can't create account
    
    # Create a default account if it doesn't exist
    default_account, created = Account.objects.get_or_create(
        name="Default Account",
        defaults={
            'slug': 'default',
            'subscription_status': 'trialing',
            'owner': owner,
        }
    )
    
    # Update all articles without an account
    Article.objects.filter(account__isnull=True).update(account=default_account)
    
    # Update all topics without an account
    Topic.objects.filter(account__isnull=True).update(account=default_account)
    
    # Update all pages without an account
    Page.objects.filter(account__isnull=True).update(account=default_account)

def reverse_set_default_account(apps, schema_editor):
    """
    Reverse the migration - set account to null for all records
    """
    Article = apps.get_model('articles', 'Article')
    Topic = apps.get_model('articles', 'Topic')
    Page = apps.get_model('articles', 'Page')
    
    Article.objects.all().update(account=None)
    Topic.objects.all().update(account=None)
    Page.objects.all().update(account=None)


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_add_account_fields'),
    ]

    operations = [
        migrations.RunPython(set_default_account, reverse_set_default_account),
    ]
