# Generated by Django 4.2.26 on 2025-11-16 09:40

from django.db import migrations


def set_default_author(apps, schema_editor):
    """
    Set a default author for existing articles that don't have one
    """
    Article = apps.get_model('articles', 'Article')
    User = apps.get_model('users', 'User')
    
    # Get the first user to be the default author
    default_author = User.objects.first()
    if default_author:
        # Update all articles without an author
        Article.objects.filter(author__isnull=True).update(author=default_author)


def reverse_set_default_author(apps, schema_editor):
    """
    Reverse the migration - set author to null for all records
    """
    Article = apps.get_model('articles', 'Article')
    Article.objects.all().update(author=None)


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_populate_account_field"),
    ]

    operations = [
        migrations.RunPython(set_default_author, reverse_set_default_author),
    ]
