# Generated by Django 4.2.26 on 2025-11-16 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("media", "0002_initial"),
        ("articles", "0004_populate_author_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="article",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="media.media",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="articles.topic",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name="topic",
            name="slug",
            field=models.SlugField(max_length=100),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["account", "status", "published_at"],
                name="articles_ar_account_e2f800_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["account", "slug"], name="articles_ar_account_52ee2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["author", "status"], name="articles_ar_author__8254d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["account", "author"], name="articles_ar_account_47d4b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(
                fields=["account", "slug"], name="articles_pa_account_74cd59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["account", "slug"], name="articles_to_account_865ea3_idx"
            ),
        ),
    ]
