# Generated by Django 4.2.26 on 2025-11-17 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("media", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articles", "0005_article_author_article_hero_image_article_topic_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleAnnotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("selected_text", models.TextField()),
                ("note", models.TextField(blank=True)),
                ("selection_start", models.IntegerField()),
                ("selection_end", models.IntegerField()),
                ("position_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("love", "Love"),
                            ("laugh", "Laugh"),
                            ("wow", "Wow"),
                            ("sad", "Sad"),
                            ("angry", "Angry"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BreakingNews",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("headline", models.CharField(max_length=300)),
                ("subheadline", models.CharField(blank=True, max_length=500)),
                ("content", models.TextField(blank=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("breaking", "Breaking"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("external_url", models.URLField(blank=True)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("click_count", models.IntegerField(default=0)),
                ("view_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("is_approved", models.BooleanField(default=True)),
                ("is_spam", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query", models.CharField(max_length=500)),
                ("result_count", models.IntegerField(default=0)),
                ("query_vector", models.JSONField(blank=True, default=list)),
                ("filters_applied", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.AddField(
            model_name="article",
            name="engagement_score",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="article",
            name="follow_up_links",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="article",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="article",
            name="media_gallery",
            field=models.ManyToManyField(
                blank=True, related_name="article_galleries", to="media.media"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="premium_excerpt",
            field=models.TextField(
                blank=True, help_text="Preview content for non-subscribers"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="related_articles",
            field=models.ManyToManyField(
                blank=True, related_name="related_to", to="articles.article"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="series_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="article",
            name="video_embed_url",
            field=models.URLField(
                blank=True, help_text="YouTube, Vimeo, or direct video URL"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["is_premium"], name="articles_ar_is_prem_b9edba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["engagement_score"], name="articles_ar_engagem_b105bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["series", "series_order"], name="articles_ar_series__25dcd9_idx"
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="series",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="cover_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="media.media",
            ),
        ),
        migrations.AddField(
            model_name="searchquery",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_queries",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="searchquery",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="articles.article",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="articles.comment",
            ),
        ),
        migrations.AddField(
            model_name="breakingnews",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="breaking_news",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="breakingnews",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="articles.article",
            ),
        ),
        migrations.AddField(
            model_name="breakingnews",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="articlereaction",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="articles.article",
            ),
        ),
        migrations.AddField(
            model_name="articlereaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article_reactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="articleannotation",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to="articles.article",
            ),
        ),
        migrations.AddField(
            model_name="articleannotation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="articles.series",
            ),
        ),
        migrations.AddIndex(
            model_name="series",
            index=models.Index(fields=["slug"], name="articles_se_slug_406f20_idx"),
        ),
        migrations.AddIndex(
            model_name="series",
            index=models.Index(
                fields=["account"], name="articles_se_account_b52fa4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(fields=["query"], name="articles_se_query_2c8fc8_idx"),
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(
                fields=["account", "user"], name="articles_se_account_1b4301_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["article", "is_approved"], name="articles_co_article_e979df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["parent"], name="articles_co_parent__5bf8ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="breakingnews",
            index=models.Index(
                fields=["priority", "is_active"], name="articles_br_priorit_f50b6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="breakingnews",
            index=models.Index(
                fields=["expires_at", "is_active"],
                name="articles_br_expires_1e180b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="breakingnews",
            index=models.Index(
                fields=["account"], name="articles_br_account_9b91ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articlereaction",
            index=models.Index(
                fields=["article", "reaction_type"],
                name="articles_ar_article_0b5828_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="articlereaction",
            unique_together={("article", "user")},
        ),
        migrations.AddIndex(
            model_name="articleannotation",
            index=models.Index(
                fields=["article", "user"], name="articles_ar_article_8da7cb_idx"
            ),
        ),
    ]
