# Generated by Django 5.0.3 on 2025-11-17 03:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("articles", "0006_articleannotation_articlereaction_breakingnews_and_more"),
        ("media", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollaborativeSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("completed", "Completed"),
                            ("locked", "Locked"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "session_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional session name for group collaboration",
                        max_length=200,
                    ),
                ),
                (
                    "current_content",
                    models.TextField(
                        blank=True, help_text="Current collaborative content state"
                    ),
                ),
                (
                    "current_title",
                    models.CharField(
                        blank=True,
                        help_text="Current collaborative title",
                        max_length=200,
                    ),
                ),
                (
                    "base_version",
                    models.IntegerField(
                        default=0, help_text="Article version this session started from"
                    ),
                ),
                (
                    "operations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of operational transforms applied",
                    ),
                ),
                (
                    "operation_sequence",
                    models.PositiveIntegerField(
                        default=0, help_text="Sequential counter for operations"
                    ),
                ),
                (
                    "allow_anonymous",
                    models.BooleanField(
                        default=False, help_text="Allow anonymous contributors"
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        default=10, help_text="Maximum number of participants"
                    ),
                ),
                (
                    "auto_save_interval",
                    models.PositiveIntegerField(
                        default=30, help_text="Auto-save interval in seconds"
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False, help_text="Lock session to prevent new joins"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Session expiration time", null=True
                    ),
                ),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborative_session",
                        to="articles.article",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SessionParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("disconnected", "Disconnected"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "cursor_position",
                    models.IntegerField(
                        default=0, help_text="Current cursor position in document"
                    ),
                ),
                ("selection_start", models.IntegerField(default=0)),
                ("selection_end", models.IntegerField(default=0)),
                (
                    "user_color",
                    models.CharField(
                        default="#0066FF",
                        help_text="Hex color for user identification",
                        max_length=7,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.collaborativesession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="collaborativesession",
            name="participants",
            field=models.ManyToManyField(
                related_name="collaborative_sessions",
                through="articles.SessionParticipant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ArticleVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                (
                    "change_summary",
                    models.CharField(
                        blank=True,
                        help_text="Brief description of changes",
                        max_length=500,
                    ),
                ),
                (
                    "is_auto_saved",
                    models.BooleanField(
                        default=False,
                        help_text="True for automatic saves, False for manual saves",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("excerpt", models.TextField(blank=True, max_length=300)),
                ("word_count", models.IntegerField(default=0)),
                ("reading_time", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        max_length=20,
                    ),
                ),
                ("media_files", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="articles.article",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="article_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="media.media",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="articles.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
                "indexes": [
                    models.Index(
                        fields=["article", "version_number"],
                        name="articles_ar_article_b76fd0_idx",
                    ),
                    models.Index(
                        fields=["created_by"], name="articles_ar_created_ed3bec_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="articles_ar_created_5cd799_idx"
                    ),
                ],
                "unique_together": {("article", "version_number")},
            },
        ),
        migrations.CreateModel(
            name="ContentTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Template display name", max_length=200),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Template description and usage guidelines",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("guide", "Guide/Tutorial"),
                            ("feature", "Feature Story"),
                            ("news", "News Article"),
                            ("opinion", "Opinion Piece"),
                            ("announcement", "Announcement"),
                            ("custom", "Custom"),
                        ],
                        default="article",
                        max_length=20,
                    ),
                ),
                (
                    "title_template",
                    models.CharField(
                        blank=True,
                        help_text="Title template with placeholders (e.g., '{Topic}: {Main Point}')",
                        max_length=500,
                    ),
                ),
                (
                    "content_structure",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured content sections with placeholders",
                    ),
                ),
                (
                    "default_content",
                    models.TextField(
                        blank=True,
                        help_text="Default content with placeholders that users can customize",
                    ),
                ),
                (
                    "default_excerpt",
                    models.TextField(
                        blank=True, help_text="Default excerpt template", max_length=300
                    ),
                ),
                (
                    "estimated_word_count",
                    models.IntegerField(
                        default=0,
                        help_text="Estimated word count for content using this template",
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this template has been used",
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Default template for this account"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Available to all users"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_templates",
                        to="accounts.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-usage_count", "name"],
                "indexes": [
                    models.Index(
                        fields=["account", "is_active"],
                        name="articles_co_account_d88208_idx",
                    ),
                    models.Index(
                        fields=["template_type", "is_active"],
                        name="articles_co_templat_83f395_idx",
                    ),
                    models.Index(
                        fields=["usage_count"], name="articles_co_usage_c_71e0ef_idx"
                    ),
                    models.Index(
                        fields=["is_default"], name="articles_co_is_defa_6c4a61_idx"
                    ),
                ],
                "unique_together": {("slug",)},
            },
        ),
        migrations.CreateModel(
            name="EditorialWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft - Author Working"),
                            ("review_requested", "Review Requested"),
                            ("in_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected - Needs Revision"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "can_publish_directly",
                    models.BooleanField(
                        default=False,
                        help_text="Skip review process for senior authors",
                    ),
                ),
                (
                    "auto_publish_on_approval",
                    models.BooleanField(
                        default=False, help_text="Automatically publish when approved"
                    ),
                ),
                ("review_history", models.JSONField(blank=True, default=list)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(blank=True, help_text="Internal editorial notes"),
                ),
                ("revision_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow",
                        to="articles.article",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_reviewer",
                    models.ForeignKey(
                        blank=True,
                        help_text="User currently assigned to review",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status"], name="articles_ed_status_039ee2_idx"
                    ),
                    models.Index(
                        fields=["current_reviewer"],
                        name="articles_ed_current_a36ada_idx",
                    ),
                    models.Index(
                        fields=["priority"], name="articles_ed_priorit_689e19_idx"
                    ),
                    models.Index(
                        fields=["due_date"], name="articles_ed_due_dat_6104ea_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OperationTransform",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sequence_number",
                    models.PositiveIntegerField(
                        help_text="Sequential operation number"
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("insert", "Insert Text"),
                            ("delete", "Delete Text"),
                            ("replace", "Replace Text"),
                            ("format", "Format Change"),
                            ("undo", "Undo Operation"),
                            ("redo", "Redo Operation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "operation_data",
                    models.JSONField(help_text="Complete operation details"),
                ),
                (
                    "previous_state",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Document state before this operation",
                    ),
                ),
                (
                    "conflicts_resolved",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of conflicts that were resolved",
                    ),
                ),
                (
                    "parent_operations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Operations this one depends on",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "client_id",
                    models.CharField(
                        blank=True,
                        help_text="Client identifier for conflict resolution",
                        max_length=100,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_history",
                        to="articles.collaborativesession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborative_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["session", "sequence_number"],
                "indexes": [
                    models.Index(
                        fields=["session", "sequence_number"],
                        name="articles_op_session_e5d2f0_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="articles_op_user_id_86dabb_idx",
                    ),
                    models.Index(
                        fields=["client_id"], name="articles_op_client__2d3e5f_idx"
                    ),
                ],
                "unique_together": {("session", "sequence_number")},
            },
        ),
        migrations.AddIndex(
            model_name="sessionparticipant",
            index=models.Index(
                fields=["session", "status"], name="articles_se_session_5b3aa7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionparticipant",
            index=models.Index(
                fields=["user", "last_activity"], name="articles_se_user_id_0bf47e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sessionparticipant",
            unique_together={("session", "user")},
        ),
        migrations.AddIndex(
            model_name="collaborativesession",
            index=models.Index(
                fields=["status", "last_activity"], name="articles_co_status_6dd8b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collaborativesession",
            index=models.Index(
                fields=["article", "status"], name="articles_co_article_e3fdad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collaborativesession",
            index=models.Index(
                fields=["expires_at"], name="articles_co_expires_ee5c6e_idx"
            ),
        ),
    ]
