# Generated by Django 5.0.3 on 2025-11-17 02:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "text_content",
                    models.TextField(help_text="The text content being analyzed"),
                ),
                (
                    "text_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA256 hash of text for caching",
                        max_length=64,
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("grammar", "Grammar Check"),
                            ("readability", "Readability Analysis"),
                            ("seo", "SEO Analysis"),
                            ("comprehensive", "Comprehensive Analysis"),
                        ],
                        default="comprehensive",
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en",
                        help_text="Language code (en, es, fr, etc.)",
                        max_length=10,
                    ),
                ),
                (
                    "results",
                    models.JSONField(
                        default=dict, help_text="Analysis results and metrics"
                    ),
                ),
                ("is_cached", models.BooleanField(default=False)),
                ("cache_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_analyses",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WritingSuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "suggestion_type",
                    models.CharField(
                        choices=[
                            ("grammar", "Grammar Suggestion"),
                            ("style", "Writing Style"),
                            ("clarity", "Clarity Improvement"),
                            ("seo", "SEO Optimization"),
                            ("tone", "Tone Adjustment"),
                            ("length", "Length Optimization"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "original_text",
                    models.TextField(
                        help_text="The original text being suggested for change"
                    ),
                ),
                (
                    "suggested_text",
                    models.TextField(help_text="The suggested replacement text"),
                ),
                (
                    "start_position",
                    models.IntegerField(
                        help_text="Character position where suggestion starts"
                    ),
                ),
                (
                    "end_position",
                    models.IntegerField(
                        help_text="Character position where suggestion ends"
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.5,
                        help_text="AI confidence in this suggestion (0-1)",
                        max_digits=3,
                    ),
                ),
                ("is_accepted", models.BooleanField(default=False)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="writing_suggestions",
                        to="accounts.account",
                    ),
                ),
                (
                    "text_analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions",
                        to="content_analysis.textanalysis",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="textanalysis",
            index=models.Index(
                fields=["account", "text_hash", "analysis_type"],
                name="content_ana_account_31662a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="textanalysis",
            index=models.Index(
                fields=["analysis_type", "language"],
                name="content_ana_analysi_ea650c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="textanalysis",
            index=models.Index(
                fields=["created_at"], name="content_ana_created_af1e6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="textanalysis",
            index=models.Index(
                fields=["cache_expires_at"], name="content_ana_cache_e_2b8b74_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="textanalysis",
            unique_together={("account", "text_hash", "analysis_type")},
        ),
        migrations.AddIndex(
            model_name="writingsuggestion",
            index=models.Index(
                fields=["text_analysis", "suggestion_type"],
                name="content_ana_text_an_5bca29_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="writingsuggestion",
            index=models.Index(
                fields=["account", "is_accepted", "is_dismissed"],
                name="content_ana_account_b2e811_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="writingsuggestion",
            index=models.Index(
                fields=["confidence_score"], name="content_ana_confide_aadd9f_idx"
            ),
        ),
    ]
