# Generated by Django 4.2.26 on 2025-11-16 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "monthly_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "yearly_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("max_users", models.IntegerField(default=1)),
                ("max_articles", models.IntegerField(default=10)),
                ("max_storage_mb", models.IntegerField(default=100)),
                ("features", models.JSONField(blank=True, default=dict)),
                (
                    "stripe_price_id_monthly",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "stripe_price_id_yearly",
                    models.CharField(blank=True, max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["monthly_price"],
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("trialing", "Trialing"),
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                            ("unpaid", "Unpaid"),
                        ],
                        default="trialing",
                        max_length=20,
                    ),
                ),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("subscription_ends_at", models.DateTimeField(blank=True, null=True)),
                ("current_article_count", models.IntegerField(default=0)),
                ("current_storage_mb", models.IntegerField(default=0)),
                ("current_user_count", models.IntegerField(default=1)),
                ("custom_domain", models.CharField(blank=True, max_length=255)),
                ("domain_verified", models.BooleanField(default=False)),
                ("stripe_customer_id", models.CharField(blank=True, max_length=100)),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription_plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.subscriptionplan",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AccountUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("editor", "Editor"),
                            ("author", "Author"),
                            ("viewer", "Viewer"),
                        ],
                        default="author",
                        max_length=20,
                    ),
                ),
                ("invited_at", models.DateTimeField(blank=True, null=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_users",
                        to="accounts.account",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["account", "role"],
                        name="accounts_ac_account_625d2c_idx",
                    ),
                    models.Index(
                        fields=["user", "role"], name="accounts_ac_user_id_3192c1_idx"
                    ),
                ],
                "unique_together": {("account", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["slug"], name="accounts_ac_slug_414a43_idx"),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["owner"], name="accounts_ac_owner_i_e99d96_idx"),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["subscription_status"], name="accounts_ac_subscri_35dac3_idx"
            ),
        ),
    ]
