# Generated by Django 5.0.3 on 2025-11-16 03:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.ImageField(upload_to="uploads/%Y/%m/")),
                ("filename", models.CharField(max_length=255)),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("file_size", models.IntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Media",
                "ordering": ["-created_at"],
            },
        ),
    ]
