# Generated by Django 5.0.3 on 2025-11-16 04:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0002_initial"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="Redirect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_path",
                    models.CharField(
                        help_text="The old URL path (without domain)",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "new_path",
                    models.CharField(
                        blank=True,
                        help_text="The new URL path (leave empty for 410)",
                        max_length=500,
                    ),
                ),
                (
                    "status_code",
                    models.CharField(
                        choices=[
                            ("301", "Permanent (301)"),
                            ("302", "Temporary (302)"),
                            ("410", "Gone (410)"),
                        ],
                        default="301",
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["old_path"],
            },
        ),
        migrations.CreateModel(
            name="MetaTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("page", "Page"),
                            ("topic", "Topic"),
                            ("custom", "Custom URL"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_id", models.UUIDField(blank=True, null=True)),
                (
                    "url_pattern",
                    models.CharField(
                        blank=True,
                        help_text="URL pattern for custom matching",
                        max_length=500,
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=60)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("meta_keywords", models.CharField(blank=True, max_length=255)),
                ("canonical_url", models.URLField(blank=True)),
                ("robots_index", models.BooleanField(default=True)),
                ("robots_follow", models.BooleanField(default=True)),
                (
                    "custom_meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional meta tags as JSON",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["content_type", "url_pattern"],
                "unique_together": {("content_type", "object_id", "url_pattern")},
            },
        ),
        migrations.CreateModel(
            name="SEOSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        help_text="Default meta title for homepage", max_length=60
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        help_text="Default meta description for homepage",
                        max_length=160,
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, help_text="Comma-separated keywords", max_length=255
                    ),
                ),
                ("og_title", models.CharField(blank=True, max_length=100)),
                ("og_description", models.CharField(blank=True, max_length=200)),
                (
                    "twitter_card",
                    models.CharField(default="summary_large_image", max_length=50),
                ),
                ("twitter_site", models.CharField(blank=True, max_length=50)),
                ("twitter_creator", models.CharField(blank=True, max_length=50)),
                ("organization_name", models.CharField(max_length=100)),
                ("organization_url", models.URLField()),
                ("google_analytics_id", models.CharField(blank=True, max_length=50)),
                ("google_search_console", models.URLField(blank=True)),
                ("bing_webmaster_tools", models.CharField(blank=True, max_length=100)),
                ("sitemap_priority", models.FloatField(default=0.8)),
                (
                    "sitemap_changefreq",
                    models.CharField(default="weekly", max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="og_images",
                        to="media.media",
                    ),
                ),
                (
                    "organization_logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="org_logos",
                        to="media.media",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seo_settings",
                        to="sites.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SitemapEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("page", "Page"),
                            ("topic", "Topic"),
                            ("home", "Homepage"),
                            ("custom", "Custom URL"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_id", models.UUIDField(blank=True, null=True)),
                ("url", models.CharField(max_length=500)),
                ("priority", models.FloatField(default=0.5)),
                (
                    "changefreq",
                    models.CharField(
                        choices=[
                            ("always", "Always"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                            ("never", "Never"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-last_modified"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "last_modified"],
                        name="seo_sitemap_content_c0e9cd_idx",
                    ),
                    models.Index(
                        fields=["last_modified"], name="seo_sitemap_last_mo_b20633_idx"
                    ),
                ],
                "unique_together": {("content_type", "object_id", "url")},
            },
        ),
    ]
