# Generated by Django 5.0.3 on 2025-11-16 04:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("subject_template", models.CharField(max_length=200)),
                ("html_template", models.TextField()),
                ("text_template", models.TextField()),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubscriberGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subject", models.CharField(max_length=200)),
                (
                    "preview_text",
                    models.CharField(
                        help_text="Text shown in email clients", max_length=150
                    ),
                ),
                ("content_html", models.TextField()),
                ("content_text", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("target_all_subscribers", models.BooleanField(default=True)),
                ("total_sent", models.PositiveIntegerField(default=0)),
                ("total_opened", models.PositiveIntegerField(default=0)),
                ("total_clicked", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_newsletters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="newsletters",
                        to="newsletter.subscribergroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=False)),
                ("is_confirmed", models.BooleanField(default=False)),
                (
                    "confirmation_token",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    "unsubscribe_token",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="newsletter_subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSend",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("bounced", "Bounced"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("open_token", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("click_token", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "newsletter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sends",
                        to="newsletter.newsletter",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newsletter_sends",
                        to="newsletter.subscriber",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="subscriber",
            index=models.Index(fields=["email"], name="newsletter__email_c1e80c_idx"),
        ),
        migrations.AddIndex(
            model_name="subscriber",
            index=models.Index(
                fields=["confirmation_token"], name="newsletter__confirm_cde183_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriber",
            index=models.Index(
                fields=["unsubscribe_token"], name="newsletter__unsubsc_cc7505_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriber",
            index=models.Index(
                fields=["is_active", "is_confirmed"],
                name="newsletter__is_acti_aa7f06_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="newslettersend",
            index=models.Index(
                fields=["newsletter", "status"], name="newsletter__newslet_02f7c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newslettersend",
            index=models.Index(
                fields=["subscriber", "status"], name="newsletter__subscri_730247_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newslettersend",
            index=models.Index(
                fields=["open_token"], name="newsletter__open_to_2e6313_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newslettersend",
            index=models.Index(
                fields=["click_token"], name="newsletter__click_t_929b14_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="newslettersend",
            unique_together={("newsletter", "subscriber")},
        ),
        migrations.AddIndex(
            model_name="newsletter",
            index=models.Index(
                fields=["status", "scheduled_at"], name="newsletter__status_e2eebf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsletter",
            index=models.Index(
                fields=["created_at"], name="newsletter__created_276d89_idx"
            ),
        ),
    ]
